version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    container_name: frontend
    image: frontend
    command: npm run dev
    env_file:
      - dev.env
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - "3300:3300"
